### ISSUE TITLE
Issues with .config 

### ISSUE THREAD

**Issue by SkylarFlux** [maltejur/discord-screenaudio#108]
Installed discord-screenaudio through the Flatpak method, but I can't find the discord-screenaudio file containing userstyles.css for adding custom CSS/themes.

**Comment by maltejur** [comment]
The relevant path for the Flatpak is `~/.var/app/de.shorsh.discord-screenaudio/config/discord-screenaudio/userstyles.css`, I should probably update the readme to explain that.
