### ISSUE TITLE
keybinds not working

### ISSUE THREAD

**Issue by GeorgiLudiq** [maltejur/discord-screenaudio#115]
the keybinds are not working even the default ones

**Comment by GeorgiLudiq** [comment]
[main] Injecting  "qwebchannel.js"
[main] Injecting  "userscript.js"
[userscript] Cannot locate Mute/Deafen/Settings button container, please report this on GitHub

**Comment by LithRakoon** [comment]
Can confirm the same thing happening here.
- Fedora 37
- KDE Plasma 5.27.2
- wayland
-  xdg-desktop-portal-kde 5.27.2

After enabling the new global shortcuts feature for every application using wayland and xwayland on Plasma 5.27 it does not recognize my keyboard shortcuts.
The only times when it works is when the screen is focused on the discord window.
![Screenshot_20230302_132917](https://user-images.githubusercontent.com/41258148/222429850-62027f55-f9b1-4050-8b3a-3ad09e17dfde.png)

**Comment by maltejur** [comment]
I have no idea what Plasma changed here. I can't find any documentation on the new "Global Shortcuts", and previously everything worked just fine on Wayland using KGlobalAccel.

**Comment by maltejur** [comment]
Nevermind the changes have nothing to do with the recent plasma update, everything works fine if I use discord-screenaudio v1.6.3. So I seem to have broken something while refactoring the code.

**Comment by maltejur** [comment]
Should be fixed in https://github.com/maltejur/discord-screenaudio/commit/96bca52d0d6e4a81384b986246937526a550916e

**Comment by yaomtc** [comment]
What about Ctrl+Q for quit? I can use Alt-F4 as a workaround but a bit odd that Ctrl+Q doesn't work

**Comment by maltejur** [comment]
@yaomtc added in https://github.com/maltejur/discord-screenaudio/commit/94b27f5b6acd815f8ca6f7b92ea31b381f2ae7fd

**Comment by yaomtc** [comment]
Thanks!
