### ISSUE TITLE
screen share not working on arch linux manjaro kde

### ISSUE THREAD

**Issue by BraydenGG97** [maltejur/discord-screenaudio#124]
Hello everyone, I recently installed Arch Linux Manjaro with KDE and decided to install the program to use the screen share feature. However, when I try to share my screen, nothing happens and the screen is not shared. What can I do? Thank you in advance for your help

**Comment by BraydenGG97** [comment]
Hello everyone, I just wanted to let you know that I was able to solve the problem on my own and no longer need assistance. Thank you for your attention and the help you offered. Thread closed.

**Comment by GroovyGab** [comment]
How did you fix it? I'm having the exact same issue on KDE Neon

**Comment by BraydenGG97** [comment]
> How did you fix it? I'm having the exact same issue on KDE Neon

It's simple just install pipewire as written on the installation tread on github
