### ISSUE TITLE
Minimum Window Size

### ISSUE THREAD

**Issue by 17hoehbr** [maltejur/discord-screenaudio#127]
Hello, love this project.

The only thing that's been bothering me is that there is no minimum window size. This means that when I launch the app it can open in extremely small windows, and users can accidentally make the windows so small you can't even see it. (see screenshots).

This is a very minor issue but it makes it very noticeable that this is not the official Discord app.
![image](https://user-images.githubusercontent.com/1351017/226147678-7e79d066-f4cf-47b1-af08-ea16207e8b99.png)
![image](https://user-images.githubusercontent.com/1351017/226147734-dc7f3998-fdd2-4c50-8b59-0e02177d3750.png)

**Comment by maltejur** [comment]
Sure. 800x300 seems to be the minimal size at which the discord UI still looks ok, so I have set the minimum size to that.

![image](https://user-images.githubusercontent.com/48161361/226179215-a57e0aef-a999-4f1b-b727-a1fb66f78c88.png)
