### ISSUE TITLE
Screenshare doesn't want to start

### ISSUE THREAD

**Issue by AzhamProdLive** [maltejur/discord-screenaudio#128]
Everytime I wanna start a screenshare, it shows me the screenshare menu, and when I click start, it just doesn't start anything at all, and doesn't allow me to click on the screenshare button anymore

I'm running Linux Mint btw

**Comment by AzhamProdLive** [comment]
more explanation here : 
Basically, when I want to screenshare my screen, it shows the menu to select the settings of the stream, and when I select the button to start, the window disappear, and doesn't start the stream at all
Another problem I had, is that running PipeWire breaks my whole sound system, is that really required to start a screenshare ?

**Comment by AzhamProdLive** [comment]
Okay, so I fixed my problem, but now when I start to stream, there is no sound on the end of the user when I stream a game (there, CSGO), any fixes ? and I ended up downloading PipeWire too

**Comment by AzhamProdLive** [comment]
Managed to fix my issue thanks to Pavu control, switched the input to my Desktop audio

**Comment by Naozumi520** [comment]
Can you explain about how did you managed to fix the issue? I'm facing the same issue and I have no idea to fix....

**Comment by AzhamProdLive** [comment]
The fix it literally given in the last message

**Comment by SamuelGogarty** [comment]
could you be a little more clear? you switched the input (as in your microphone?) to your desktop audio? what?

**Comment by AzhamProdLive** [comment]
![image](https://github.com/maltejur/discord-screenaudio/assets/73955243/424b86a7-91c6-4a79-baaa-8fe18c0dde29)
