### ISSUE TITLE
Disclose use and license of arRPC

### ISSUE THREAD

**Issue by CanadaHonk** [maltejur/discord-screenaudio#130]
Hi! Cool project. You use [arRPC](https://github.com/OpenAsar/arRPC) without disclosing usage or including its license. Could you do that please? Thanks!

**Comment by CanadaHonk** [comment]
Also pls report any bugs/issues you find to me and I'd be happy to try and fix ;)

**Comment by maltejur** [comment]
Hi, would that look ok?

![Screenshot_20230323_225328](https://user-images.githubusercontent.com/48161361/227373182-60d1992a-3813-4fb0-9498-a6d292bfd35a.png)

I am not sure exactly how the copyright notice should look like since the MIT license if pretty vague on that.

**Comment by CanadaHonk** [comment]
LGTM! Thanks.

**Comment by maltejur** [comment]
08cb713e8c7cc5a294551d3f9ec8859e9e47b52d
