### ISSUE TITLE
Any chance of this being available on Wayland as well?

### ISSUE THREAD

**Issue by Smoukus** [maltejur/discord-screenaudio#14]

**Comment by maltejur** [comment]
Maybe. Does [this method](https://github.com/edisionnano/Screenshare-with-audio-on-Discord-with-Linux) work for you? If yes, there could be a good chance it is possible.

**Comment by Maciejka1** [comment]
It is in work, we have to wait because wayland screen sharing is secured so if someone got access to your screen remotely they would see black screen only. We just have to wait.

**Comment by edisionnano** [comment]
May work with QTWEBENGINE_CHROMIUM_FLAGS=--enable-features=WebRTCPipeWireCapturer

**Comment by maltejur** [comment]
That should indeed fix the problem, at least it did for me. I added that flag to the code: https://github.com/maltejur/discord-screenaudio/commit/ee0c66762d409272e9fc9b92d7745e46a4b8aa46, so the issue should hopefully be fixed

**Comment by doubledge-spec** [comment]
Doesn't work for me. The sound works, but for me and friends, the stream is just a loading screen.

**Comment by doubledge-spec** [comment]
I installed them before testing. I read the other thread which has this info before trying.
