### ISSUE TITLE
Application not in the audio source list (Looking Glass Client)

### ISSUE THREAD

**Issue by regunakyle** [maltejur/discord-screenaudio#141]
Hi,

I have an application that just refuses to show up on the audio source list. (To be precise, it is [Looking Glass Client](https://looking-glass.io/) built with Pipewire support)

I have no idea how to debug this. Is there a list of common causes of this?

**Comment by maltejur** [comment]
I think this is because Looking Glass doesn't work like a ordinary Pipewire application but integrates deeper into the system. As far as I can tell, it also doesn't show up in the KDE audio settings:

![image](https://user-images.githubusercontent.com/48161361/232421251-6d8dc131-e32f-4838-940c-42cca8429f3a.png)

So I have no idea how to change that, but if you are able to make it show up in a program like [helvum](https://gitlab.freedesktop.org/pipewire/helvum), it probably also works with this program.

**Comment by regunakyle** [comment]
> I think this is because Looking Glass doesn't work like a ordinary Pipewire application but integrates deeper into the system. As far as I can tell, it also doesn't show up in the KDE audio settings:
> 
> ![image](https://user-images.githubusercontent.com/48161361/232421251-6d8dc131-e32f-4838-940c-42cca8429f3a.png)
> 
> So I have no idea how to change that, but if you are able to make it show up in a program like [helvum](https://gitlab.freedesktop.org/pipewire/helvum), it probably also works with this program.

I see. I will ask the Looking Glass devs about this then. Thanks for your reply!

**Comment by regunakyle** [comment]
> I think this is because Looking Glass doesn't work like a ordinary Pipewire application but integrates deeper into the system. As far as I can tell, it also doesn't show up in the KDE audio settings:
> 
> ![image](https://user-images.githubusercontent.com/48161361/232421251-6d8dc131-e32f-4838-940c-42cca8429f3a.png)
> 
> So I have no idea how to change that, but if you are able to make it show up in a program like [helvum](https://gitlab.freedesktop.org/pipewire/helvum), it probably also works with this program.
![Screenshot_20230417_204645](https://user-images.githubusercontent.com/60984878/232488502-deb2a97a-b78d-4a88-8e47-dc2a82c59e9d.png)
![Screenshot_20230417_205010](https://user-images.githubusercontent.com/60984878/232489384-e9fce1f2-1837-4d3f-b9db-22847b16098e.png)

Weird. Both KDE audio setting and Helvum shows the Looking Glass client. 
It is still not in the audio source list though.

**Comment by regunakyle** [comment]
> > I think this is because Looking Glass doesn't work like a ordinary Pipewire application but integrates deeper into the system. As far as I can tell, it also doesn't show up in the KDE audio settings:
> > ![image](https://user-images.githubusercontent.com/48161361/232421251-6d8dc131-e32f-4838-940c-42cca8429f3a.png)
> > So I have no idea how to change that, but if you are able to make it show up in a program like [helvum](https://gitlab.freedesktop.org/pipewire/helvum), it probably also works with this program.
> 
> ![Screenshot_20230417_204645](https://user-images.githubusercontent.com/60984878/232488502-deb2a97a-b78d-4a88-8e47-dc2a82c59e9d.png) ![Screenshot_20230417_205010](https://user-images.githubusercontent.com/60984878/232489384-e9fce1f2-1837-4d3f-b9db-22847b16098e.png)
> 
> Weird. Both KDE audio setting and Helvum shows the Looking Glass client. It is still not in the audio source list though.

Cont'd
![Screenshot_20230417_205638](https://user-images.githubusercontent.com/60984878/232490773-b28d1b90-5fef-4d8a-a368-cbc608cee717.png)

**Comment by maltejur** [comment]
Huh, that is interesting. Does the [All Desktop Audio] capture the audio?

**Comment by regunakyle** [comment]
> Huh, that is interesting. Does the [All Desktop Audio] capture the audio?

No. It captures other applications though (e.g. flatpak Chrome/Firefox and non-flatpak [Strawberry](https://www.strawberrymusicplayer.org/) on host)

**Comment by regunakyle** [comment]
Note: I am on Fedora KDE 37.
libpipewire v 0.3.69
discord-screenaudio Version 1.8.0

I will try building the Looking Glass again to see if it fixes the problem

**Comment by maltejur** [comment]
Okay I am now also able to reproduce looking glass showing up in helvum and I think I know what the issue is. I am working on a fix.

**Comment by regunakyle** [comment]
> Okay I am now also able to reproduce looking glass showing up in helvum and I think I know what the issue is. I am working on a fix.

Thanks! I appreciate your work, without this app I have to run Discord inside Windows, lol.

**Comment by maltejur** [comment]
Okay for now it seems I would have to match a much broader scope of Pipewire nodes to also match the Looking Glass one. Maybe there is a cleaner way to do this, maybe I could also hide it behind a preference.

![image](https://user-images.githubusercontent.com/48161361/232497488-fdf01615-0c12-4d27-b6f5-ac28e09a4954.png)

**Comment by regunakyle** [comment]
> Okay for now it seems I would have to match a much broader scope of Pipewire nodes to also match the Looking Glass one. Maybe there is a cleaner way to do this, maybe I could also hide it behind a preference.
> 
> ![image](https://user-images.githubusercontent.com/48161361/232497488-fdf01615-0c12-4d27-b6f5-ac28e09a4954.png)

Most other applications work out of the box. Maybe this is a problem with Looking Glass?
Anyway I would suggest making this togglable.

**Comment by maltejur** [comment]
I was able to make everything work as expected without all the other stuff by using some other PipeWire metadata. All of that is pushed to master, so if you are able to compile it yourself you could test right now if the changes work for your.

**Comment by regunakyle** [comment]
> I was able to make everything work as expected without all the other stuff by using some other PipeWire metadata. All of that is pushed to master, so if you are able to compile it yourself you could test right now if the changes work for you.

I built the binary inside a Fedora 37 [distrobox](https://github.com/89luca89/distrobox) with the required dependencies. Audio streaming works, but for some reason there is no popup window to let me choose the video source, so no video streaming. Maybe this is a distrobox issue.

**Comment by regunakyle** [comment]
> > I was able to make everything work as expected without all the other stuff by using some other PipeWire metadata. All of that is pushed to master, so if you are able to compile it yourself you could test right now if the changes work for you.
> 
> I built the binary inside a Fedora 37 [distrobox](https://github.com/89luca89/distrobox) with the required dependencies. Audio streaming works, but for some reason there is no popup window to let me choose the video source, so no video streaming. Maybe this is a distrobox issue.

I built the binary in a brand new Fedora KDE 37 VM. Same issue (No video output selector). The flatpak version works correctly though.

**Comment by regunakyle** [comment]
The new version in Flathub works perfectly. Thank you for your work!

**Comment by maltejur** [comment]
Great to hear. Weird that the version you compiled yourself had that issue, but if the Flatpak worked out in the end I guess thats fine.
