### ISSUE TITLE
The program crashes when I try to change the scale of the interface

### ISSUE THREAD

**Issue by Vitalya-code** [maltejur/discord-screenaudio#143]
The program crashes when I try to change the scale of the interface using 'CTRL+scroll up' or 'CTRL+scroll down

i use flatpak version

[log.txt](https://github.com/maltejur/discord-screenaudio/files/11255739/log.txt)

**Comment by maltejur** [comment]
I was able to reproduce this issue and for me I have fixed it with https://github.com/maltejur/discord-screenaudio/commit/7b6e8fc4735d62ff104f52daed842f5dcd3bf4d3

If you are able to, can you compile the program yourself from master to check if it is fixed for you?

**Comment by Vitalya-code** [comment]
Ok i will try it later, thank you for your work!

**Comment by Vitalya-code** [comment]
Yes, the problem seems to be fixed, thank you
