### ISSUE TITLE
JACK support

### ISSUE THREAD

**Issue by noneistaken** [maltejur/discord-screenaudio#147]
I have not looked at the project's source code and therefore cannot assess the difficulty of implementing this, but I'm a JACK user (I do a lot of very low-latency audio which Pipewire is simply not capable of doing) so this is a request for JACK support.

**Comment by maltejur** [comment]
While this would be really great to have, I probably don't have the time to implement it. I am of course open to any pull requests though.

**Comment by noneistaken** [comment]
If you don't mind dumping some more info of how & where in the code this project interfaces with Pipewire, specifically how audio data is passed around, I will make a pull request.

**Comment by noneistaken** [comment]
Closing this issue as it is too much out of scope. Chromium (and thus QtWebEngine) does not support JACK (and Chromium devs are too stubborn to add support for that).
For now JACK users should bridge PulseAudio and use edisionnano's instructions for PulseAudio.
