### ISSUE TITLE
Streaming suddenly not working properly on wayland.

### ISSUE THREAD

**Issue by queenbiscuit311** [maltejur/discord-screenaudio#159]
I tried streaming on wayland not too long ago and everything worked fine, but now I can't stream my full screen anymore. Also, streaming will sometimes destroy performance for some reason. Streaming on X11 is working fine, and I've never had this before on wayland and screen sharing is working perfectly fine on the web app through opera, except obviously no sound.

**Comment by queenbiscuit311** [comment]
For more information: I'm on arch on kde plasma, using the aur build of the program.

**Comment by Jimbleton115** [comment]
I was having this issue as well on Fedora 38 KDE; I have GNOME as well, so I tried it on there and no such issues were present. Must be some kind of KDE issue

**Comment by ImUrX** [comment]
Im on gnome and i cant fullscreen screenshare.
This is spammed on logs `Failed to get video stream: Zero size.`

**Comment by queenbiscuit311** [comment]
Issue seems to have been solved by an update to kwin, hopefully it stays fixed.
