### ISSUE TITLE
On first launch, virtmic overrides microphone after you join vc.

### ISSUE THREAD

**Issue by doubledge-spec** [maltejur/discord-screenaudio#16]
in #7 a method for refreshing audio devices was achieved. The problem is that even if it's not selected the virtmic overrides your microphone after you join vc so you'll need to fiddle with mic settings. Even if discord is set to the correct mic, pavucontrol shows virtmic being used, so you really need to fiddle. If possible, maybe have it run and then kill it? Discord lets you choose other mics after it detects the virtmic and after that first virtmic is killed.

**Comment by doubledge-spec** [comment]
Discord lets you choose other mics, after it detects the virtmic and even after that first virtmic is killed.

**Comment by maltejur** [comment]
> The problem is that even if it's not selected the virtmic overrides your microphone after you join vc so you'll need to fiddle with mic settings.

Weird, it works for me without needing to change any settings.

> Discord lets you choose other mics after it detects the virtmic and after that first virtmic is killed.

From my testing this is not the case, the virtmic has to stay active. But maybe I can find another soultion.

**Comment by maltejur** [comment]
Since I can't reproduce the issue, can you try something out for me? Could you build the [testing_default_mic](https://github.com/maltejur/discord-screenaudio/tree/testing_default_mic) branch, run `./discord-screenaudio --virtmic None` and send me the output of that?

**Comment by doubledge-spec** [comment]
will do, is the method for getting the specific branch?:
1. clone it
2. switch to testing_default_mic with `git switch testing_default_mic`
3. pull? `git pull `

**Comment by doubledge-spec** [comment]
[logs.txt](https://github.com/maltejur/discord-screenaudio/files/9198527/logs.txt)
So I tried to do what you asked.

**Comment by maltejur** [comment]
Thanks. Hm this means that the default microphone isn't changed after the virtmic is created. So I have no idea why it isn't working for you.

**Comment by doubledge-spec** [comment]
Alright, will close. If I discover a reproducible way to create this, it'll make a new issue
