### ISSUE TITLE
After restart, you need to toggle desktop notifications for them to show up.

### ISSUE THREAD

**Issue by doubledge-spec** [maltejur/discord-screenaudio#17]
Notification daemon is xfce4-notifyd
DE is Xfce 4.16
Distro is EndeavourOS (arch linux based distro)

**Comment by maltejur** [comment]
Fixed in https://github.com/maltejur/discord-screenaudio/commit/fa83e2d9a84c5a4c9c8adae11eff2fd7beb3c2af
