### ISSUE TITLE
Clicking on notifications do nothing

### ISSUE THREAD

**Issue by doubledge-spec** [maltejur/discord-screenaudio#18]
Notification daemon is xfce4-notifyd
DE is Xfce 4.16
Distro is EndeavourOS (arch linux based distro)

Clicking on notifications in firefox and chromium bring you to the message.

**Comment by maltejur** [comment]
This seems to be a general QtWebEngine and even Qt limitation. Even their example for desktop notifications isn't clickable for me: https://doc.qt.io/qt-5/qtwidgets-desktop-systray-example.html

**Comment by maltejur** [comment]
I could create custom notifications using [knotifications](https://api.kde.org/frameworks/knotifications/html/), but that is low priority

**Comment by doubledge-spec** [comment]
Understandable.

**Comment by maltejur** [comment]
Fixed in https://github.com/maltejur/discord-screenaudio/commit/ef221d4574bf473a2a06783a9d5af771221c8bb3
