### ISSUE TITLE
Discord-screenaudio fully blank screen -UNABLE TO LOAD

### ISSUE THREAD

**Issue by DuskCS04** [maltejur/discord-screenaudio#182]
So i ran the program through the terminal with the flatpak installation and this is the what errors i get in the terminal and the screen of discord... please fix this since it literally makes the app unable to function whatsoever and forcing me to use a different discord client. I love this client since its the only one that can do audio sharing but it has its issues. 
![Screenshot from 2023-09-17 23-35-02](https://github.com/maltejur/discord-screenaudio/assets/65992721/859acb02-5335-4006-bb3f-98856b43849c)
![Screenshot from 2023-09-17 23-36-05](https://github.com/maltejur/discord-screenaudio/assets/65992721/7d7bb5ae-53c1-463a-a032-482e67edda79)

**Comment by Corban-Lee** [comment]
Why would you close as completed without saying anything?

Did you find a fix, if so could you share it?
