### ISSUE TITLE
Window status is not retained after exiting fullscreen video.

### ISSUE THREAD

**Issue by doubledge-spec** [maltejur/discord-screenaudio#19]
this client:
https://user-images.githubusercontent.com/56917537/181297778-536e672f-6784-4535-9bf8-7a0c7b4e4cfa.mp4

PTB:
https://user-images.githubusercontent.com/56917537/181298055-32238cd7-9269-4394-a808-44275bfaf61a.mp4

**Comment by maltejur** [comment]
Fixed in https://github.com/maltejur/discord-screenaudio/commit/5f9211f98ff9754d88101c93f771f6e40636b578
