### ISSUE TITLE
Continued issues after v1.9.2

### ISSUE THREAD

**Issue by tinyCatzilla** [maltejur/discord-screenaudio#207]
I am using Arch Linux with Hyprland, and despite the recently approved patch, I am still having issues with the application that only manifested after Discord's recent changes. Specifically, clicking on _anything_ will immediately crash this application.

My system and packages are fully up to date, and I am not sure how to proceed with troubleshooting. I would greatly appreciate some guidance on which (and where) are the relevant crash logs, so I can begin investigating these continued issues.

**Comment by scramble45** [comment]
Same problem, eventually crashes subsided and I am now unable to stream with mic/game at the same time.

**Comment by tinyCatzilla** [comment]
@scramble45 I installed the flatpak and everything works flawlessly for me. Not sure why AUR version wasn't working.

**Comment by scramble45** [comment]
> @scramble45 I installed the flatpak and everything works flawlessly for me. Not sure why AUR version wasn't working. 

Pretty sure I'm using the flatpak version but lemme blow it away and redownload and see if that helps.

**Comment by tinyCatzilla** [comment]
@scramble45 Also, be sure to update. For me, "reinstalling" wasn't enough, I still had to manually update. Closing issue now
