### ISSUE TITLE
Notifications do not work at all after knotifications implementation

### ISSUE THREAD

**Issue by doubledge-spec** [maltejur/discord-screenaudio#22]
EndeavourOS
Xfce 4.16
Notification daemon is xfce4-notifyd

Notifications do not show up. Nothing shows up in logs when notifications are received.

**Comment by maltejur** [comment]
Do you have `knotifications` installed?

**Comment by doubledge-spec** [comment]
I compiled the build after installing knotifications, it gave me an error that it couldn't find it, when i tried prepping the build folder the first time.

**Comment by doubledge-spec** [comment]
This is what I did before submitting this github issue.

**Comment by maltejur** [comment]
Make sure that you actually install the files. KNotifications expects a certain file in a certain place.

**Comment by doubledge-spec** [comment]
ehm, could you be more specific?

**Comment by maltejur** [comment]
Run `sudo cmake --install build`, this will install discord-screenaudio to the system

**Comment by doubledge-spec** [comment]
they work!.
again, i highly suggest an aur package. Thank you for your time.

**Comment by doubledge-spec** [comment]
ah, i made a mistake, i'm unsure on how to uninstall the source package.

**Comment by maltejur** [comment]
If you want to revert the install command, run `sudo xargs rm -f <build/install_manifest.txt`
