### ISSUE TITLE
Stream desktop audio minus Discord itself

### ISSUE THREAD

**Issue by MrKingMichael** [maltejur/discord-screenaudio#25]
What the title says. This will allow you to stream all PC audio, with the exception of Discord.

**Comment by maltejur** [comment]
So basically an option to stream the whole desktop audio minus Discord itself?

**Comment by MrKingMichael** [comment]
Exactly!

**Comment by im-viriv** [comment]
This would be cool since even the official Discord implementation can't do that

**Comment by maltejur** [comment]
I implemented this on the master branch. Can one of you test it before I create a new release?

**Comment by StayBlueee** [comment]
> I implemented this on the master branch. Can one of you test it before I create a new release?

Works for me :+1:

**Comment by im-viriv** [comment]
same for me :+1:

**Comment by maltejur** [comment]
Thanks for testing, v1.3.0 is released now :)

**Comment by MrKingMichael** [comment]
Thank you so much for implementing this! The fact that we have such a feature exclusively on Linux without Discord officially supporting it is mind-blowing.
