### ISSUE TITLE
Offline build support

### ISSUE THREAD

**Issue by VortexAcherontic** [maltejur/discord-screenaudio#3]
Hello there, while attempting to build this project on OBS (open build service) I noticed you do use git submodules and cloning some git release of rohrkabel directly into your discord-screeaudio source directory at build time.

This is generally a bad idea as most build services like those for openSUSE (OBS), Debian, Fedora, Ubuntu, flatpak and others do build their packages offline.

In order to allow for offline building I do the following:

- Provide the ~~latest~~ rohrkabel ~~1.2~~ source archive at the currently required git revision
- Unpack the source archive into the top level source directory of discord-screenaudio in a subdirectory called rohrkabel
- Patch the discord-screenaudio CMakeLists.txt as follows:
````
diff -rub discord-screenaudio-1.0.0-rc.5/CMakeLists.txt discord-screenaudio-1.0.0-rc.5-patched/CMakeLists.txt
--- discord-screenaudio-1.0.0-rc.5/CMakeLists.txt	2022-07-20 19:06:02.000000000 +0200
+++ discord-screenaudio-1.0.0-rc.5-patched/CMakeLists.txt	2022-07-25 20:59:37.944682253 +0200
@@ -24,12 +24,7 @@
 
 include(FetchContent)
 
-FetchContent_Declare(
-  rohrkabel 
-  GIT_REPOSITORY "https://github.com/Soundux/rohrkabel" 
-  GIT_TAG "d87403f48d3a95aa4bcf4cd60112d9e4bb090d5d"
-)
-FetchContent_MakeAvailable(rohrkabel)
+add_subdirectory(rohrkabel)
 
 add_executable(discord-screenaudio ${discord-screenaudio_SRC})
````

The final source directory then looks as follows:

````
./discord-screenaudio-1.0.0-rc.5/
| assets/
| build/
| CMakeLists.txt
| LICENSE
| README.md
| resources.qrc
| rohrkabel/
| scripts/
| src/
````

It would be great to allow for build flags to swap between offline build and online build.

Kind regards,  
V.

**Comment by maltejur** [comment]
Good point, I'll add something like this. Or I may even switch completely to a submodule.

**Comment by VortexAcherontic** [comment]
With version 1.0.0-rc6 I would consider this as closed as there is no need to manually patch the CMakeList.txt.  
Many thanks for the fast work ❤️

**Comment by maltejur** [comment]
@VortexAcherontic just letting you know, for v1.0.0 I implemented a mechanism which automatically pulls the current version from git tags. If you build from a tarball, you have to provide it manually like in the [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=discord-screenaudio#n24).

**Comment by VortexAcherontic** [comment]
@maltejur Thanks for letting me know. Already doing this since RC 5 😄
