### ISSUE TITLE
Cannot screenshare windows which do not have audio

### ISSUE THREAD

**Issue by StayBlueee** [maltejur/discord-screenaudio#30]
Similar to issue #27, I don't expect this issue to actually be fixed as it is out of the scope of the project's intended purpose, but I figured I'd open it anyway just because it's something that can be improved.

As the title says, there's no way to screen share a window that does not have an active audio stream. Maybe this could be like a toggle in the stream dialog window?

**Comment by maltejur** [comment]
I am not sure what you mean. I can very well share a window that doesn't have an audio stream:

![Screenshot_20220804_111340](https://user-images.githubusercontent.com/48161361/182810659-9df5cb86-3982-47ba-9f88-c5881b5aa957.png)

Or are you talking about sharing the audio? So do you want to select `spotify` for audio share, even before Spotify opens?

**Comment by StayBlueee** [comment]
> I am not sure what you mean. I can very well share a window that doesn't have an audio stream:
> 
> ![Screenshot_20220804_111340](https://user-images.githubusercontent.com/48161361/182810659-9df5cb86-3982-47ba-9f88-c5881b5aa957.png)
> 
> Or are you talking about sharing the audio? So do you want to select `spotify` for audio share, even before Spotify opens?

It's probably because I am on X11 (blame Nvidia), but I don't see the application in the dialog window that pops up if there is no active audio stream in said application.

**Comment by maltejur** [comment]
But are you even able to stream the video of an application which has audio? That would be news to me.

**Comment by StayBlueee** [comment]
> But are you even able to stream the video of an application which has audio? That would be news to me.

Not sure what exactly you mean by this but the stream does indeed work fine on X11.

**Comment by maltejur** [comment]
What I am asking is if you are able to share a individual application window like this:

![image](https://user-images.githubusercontent.com/48161361/182822378-97b99e27-87d2-4951-8b1c-9d4f98bf25da.png)

**Comment by StayBlueee** [comment]
> What I am asking is if you are able to share a individual application window like this:
> 
> ![image](https://user-images.githubusercontent.com/48161361/182822378-97b99e27-87d2-4951-8b1c-9d4f98bf25da.png)

Oh, no, not yet. I noticed you made a new branch which hopes to fix the issues but up until now I’ve had it share my main screen no matter what application I select.

**Comment by maltejur** [comment]
Then I don't really understand the issue. The dropdown is only for selecting the audio input, so an application without audio wouldn't make sense in it.

**Comment by StayBlueee** [comment]
> Then I don't really understand the issue. The dropdown is only for selecting the audio input, so an application without audio wouldn't make sense in it.

Okay, I get what you are saying now. You're saying since we're sharing the whole screen anyway we don't have to worry about what application they can select or not. Makes sense, but what if you wanted to screen share an application like visual studio code which has no audio once your fix for X11 is finished?

**Comment by maltejur** [comment]
Once my fix is finished, this behaviour of course will chane

**Comment by StayBlueee** [comment]
> Once my fix is finished, this behaviour of course will change.

Okay, cool, then this issue can be closed! :)
