### ISSUE TITLE
Client won't start

### ISSUE THREAD

**Issue by MakS1mKa228** [maltejur/discord-screenaudio#31]
![image](https://user-images.githubusercontent.com/49811239/183261600-5d8c184f-992a-41c8-8823-613eccf47ad0.png)

**Comment by maltejur** [comment]
Does [qutebrowser](https://qutebrowser.org/) or [this](https://github.com/qt/qtwebengine/tree/dev/examples/webenginewidgets/minimal) example work for you? Also, what system are you on?

**Comment by MakS1mKa228** [comment]
Hm. qutebrowser has the same error. I am using ArchLinux with bspwm
![image](https://user-images.githubusercontent.com/49811239/183268276-26d0d183-0893-4956-80ab-3273294b0563.png)

**Comment by maltejur** [comment]
It seems then that something with your Arch install is broken. Are your graphics drivers up to date? Also, does [this](https://github.com/qutebrowser/qutebrowser/issues/3276#issuecomment-347689668) help?
