### ISSUE TITLE
Brown noise randomly passing through to the mic

### ISSUE THREAD

**Issue by MrKingMichael** [maltejur/discord-screenaudio#32]
This has been a thing for a while now, some brown noise appears to pass through to Discord with the mic input at random regardless of whether you're streaming or not, and it appears to fluctuate in volume, too. You can tell that it's happening by simply being quiet and watching the green circle around your profile picture appear. I can't reproduce it on the regular Discord client, even with all voice processing effects disabled, but can on discord-screenaudio with the same settings.

I've recorded my friend's microphone for you to understand what it sounds like: https://mega.nz/file/IsR1lZDZ#RR9bM7G_mcJs-gRpbz3MeQugYEL_2hn0vSNtkf1PA4A

It doesn't appear to be an issue exclusively on his end, since other people have reported that they hear the same noise coming from my mic, too. One way to lessen the impact of the issue is to increase the input sensitivity, but it remains an issue.

We're both on Pipewire 0.3.56, Wireplumber 0.4.11-2.

**Comment by Flanisch** [comment]
This is caused by discords "Automatic Gain Control" setting under `Voice & Video`. It seems like this build of discord always has it enabled no matter what you set it as.

**Comment by maltejur** [comment]
Does the same happen on Discord Web. If yes, I would say this isn't a bug.
