### ISSUE TITLE
Consider submitting an implementation of this for Webcord

### ISSUE THREAD

**Issue by orowith2os** [maltejur/discord-screenaudio#33]
As the title says, maybe this could be implemented in Webcord? Webcord uses Electron and the web version of Discord, so I don't know how easy this would be to port, but it could be looked into. As Webcord also uses the freedesktop Flatpak runtime, and the KDE one builds on top of that, it might just require a runtime change to work properly (for the Flatpak).

**Comment by maltejur** [comment]
See https://github.com/SpacingBat3/WebCord/issues/154
