### ISSUE TITLE
Any way to use Discord RPC?

### ISSUE THREAD

**Issue by Jolonte** [maltejur/discord-screenaudio#37]
Is there any way for the Discord RPC client to detect games from Lutris or Steam?

I found some interesting libraries:

- [Wine Discord IPC Bridge](https://github.com/0e4ef622/wine-discord-ipc-bridge)
- [rpc wine](https://github.com/mellowagain/rpc-wine)
- [pypresence](https://pypi.org/project/pypresence/)

**Comment by StayBlueee** [comment]
> Is there any way for the Discord RPC client to detect games from Lutris or Steam?
> 
> I found some interesting libraries:
> 
>     * [Wine Discord IPC Bridge](https://github.com/0e4ef622/wine-discord-ipc-bridge)
> 
>     * [rpc wine](https://github.com/mellowagain/rpc-wine)
> 
>     * [pypresence](https://pypi.org/project/pypresence/)

This project interfaces with the web version of Discord, so I don't believe it's possible. Maybe if there is some sort of endpoint or something that makes it possible it can be done? In any other case, don't see it happening any time soon.

**Comment by Jolonte** [comment]
> > Is there any way for the Discord RPC client to detect games from Lutris or Steam?
> > I found some interesting libraries:
> > ```
> > * [Wine Discord IPC Bridge](https://github.com/0e4ef622/wine-discord-ipc-bridge)
> > 
> > * [rpc wine](https://github.com/mellowagain/rpc-wine)
> > 
> > * [pypresence](https://pypi.org/project/pypresence/)
> > ```
> 
> This project interfaces with the web version of Discord, so I don't believe it's possible. Maybe if there is some sort of endpoint or something that makes it possible it can be done? In any other case, don't see it happening any time soon.

oh yes, I hope it works somehow, I made the suggestion because I really like this client because it is optimized and for me it was the only thing missing. I don't think it's something that will be missed.
