### ISSUE TITLE
File uploading does not work in Flatpak

### ISSUE THREAD

**Issue by kevin0xf** [maltejur/discord-screenaudio#43]
As the title says, upon uploading a file via discord-screenaudio, I am met with an error.
![image](https://user-images.githubusercontent.com/55111852/188310479-c6c03b90-1550-43b7-8865-00a5079e5e94.png)

**Comment by maltejur** [comment]
I can not reproduce this, can you share some steps that lead to that error and maybe the file you are trying to upload?

**Comment by kevin0xf** [comment]
The file didn't matter.
I can state some system information though.
I'm on Arch Linux 5.19.5-arch1-1 running the GNOME desktop environment with the [wayland](https://wiki.archlinux.org/title/wayland) display server.

Upon compiling discord-screenaudio for my machine, the issue has resolved itself automatically, beforehand I was using the version on flathub.

**Comment by maltejur** [comment]
Great to hear that you resolved the issue, but it seems this still is an issue with the Flatpak.

**Comment by maltejur** [comment]
This probably has something to do with the Flatpak sandboxing and missing filesystem permissions.

**Comment by maotovisk** [comment]
it's flatpak sandboxing for sure

you can use the flatpak override command or flatseal to expose the filesystem, solving the problem.

**Comment by maltejur** [comment]
The filepicker should be still working btw, I think this issue only affects drag-and-drop. I am not sure if I want to add `--filesystem=host` though to fix the drag-and-drop issue (that kind of goes against the flatpak sandboxing).

**Comment by NelloKudo** [comment]
Yeah the only issue is flatpak sandboxing, it is a thing even with Discord's official client.
The fix is to simply give access using Flatseal to the needed folders or rather to /home files.

https://streamable.com/2nuts3

I think you can close the issue, not really a clientproblem

**Comment by maltejur** [comment]
This should still be fixed for the flatpak imo, I'll do that later

**Comment by maltejur** [comment]
Fixed in https://github.com/flathub/de.shorsh.discord-screenaudio/commit/65fdc8809e34ab7bf7effbaa6a2381ed5aa9a1ca

**Comment by maltejur** [comment]
Fyi this behaviour has been changed again in https://github.com/flathub/de.shorsh.discord-screenaudio/pull/11, see https://github.com/maltejur/discord-screenaudio#drag-and-drop-doesnt-work-in-the-flatpak.
