### ISSUE TITLE
No camera detected in Pop OS

### ISSUE THREAD

**Issue by Falladis** [maltejur/discord-screenaudio#46]
Hi there, everything works amazingly however my camera is not available. Any way to fix this?

**Comment by Falladis** [comment]
flatpak version did not detect camera, however building myself made it work.

**Comment by Falladis** [comment]
built version > flatpak

**Comment by maltejur** [comment]
This should still be fixed for the flatpak and the fix is probably just to change some flatpak permissions.

**Comment by maltejur** [comment]
Fixed in https://github.com/flathub/de.shorsh.discord-screenaudio/commit/e551517adebfb2b3e202d51da192745e2cb2b797
