### ISSUE TITLE
Changing resolution or fps for stream doesn't work

### ISSUE THREAD

**Issue by Copysiper** [maltejur/discord-screenaudio#49]
I have discord nitro classic, but choosing any options (resolution or fps) doesn't work: stream always starts at 720p 30 fps (when my subscription allows streaming up to 1080p 60 fps, which works when using usual discord application).

**Comment by maltejur** [comment]
Discord always displays that it is streaming at 720p30 in this client. Could you test if you actual stream resolution is different than the one displayed?

**Comment by Copysiper** [comment]
> Discord always displays that it is streaming at 720p30 in this client. Could you test if you actual stream resolution is different than the one displayed?

Ok, I'll try to check it. By the way, what should happen if I choose the quality and fps which is higher than available with my subscription?

**Comment by tridoxx** [comment]
hello I have the same problem, I have a 2K monitor and the premium discord, which I put this month to test the audio transmission, but when streaming and putting a higher resolution it only shows 720 30fps, when in the configuration I select 2k 60fps

**Comment by tridoxx** [comment]
today i update, and its working

**Comment by maltejur** [comment]
> today i update, and its working

I've fixed the wrongly displayed resolution yesterday, good to see that that works.

> By the way, what should happen if I choose the quality and fps which is higher than available with my subscription?

The quality selector here isn't tied to Discord Nitro.

**Comment by tridoxx** [comment]
hi @maltejur thanks for the great work are you doing with this, your must work on discord  :3, a little update, idk if is my net conection maybe, but a partnert say that i share screen on 2k for example, discord show for him, that is on 720 30fps, maybe mi net error or my net error, so discord change the resolutión, but when i share 720 60fps, he see the streaming well, sorry for me english

**Comment by maltejur** [comment]
@tridoxx the resolution text displayed in your friends client does not reflect the actual resolution. It may show 720p30, but the stream should actually be in 2k.
