### ISSUE TITLE
App does not launch on Zorin 16.1

### ISSUE THREAD

**Issue by AlooTheAloo** [maltejur/discord-screenaudio#55]
App installed from software store. On launch, nothing happens. Tried installing from source and directly from flatpak, same result. Might have to do with ubuntu version.

**Comment by maltejur** [comment]
> Might have to do with ubuntu version.

Probably. Can you try the fix mentioned [here](https://github.com/Soundux/rohrkabel#%EF%B8%8F-problematic-distributions)?
