### ISSUE TITLE
Installing Fedora (and other redhad-based) building dependencies

### ISSUE THREAD

**Issue by xurich-xulaco** [maltejur/discord-screenaudio#63]
As far as I know

`dnf install cmake qt5-qtbase-devel qt5-qtwebengine-devel kf5-knotifications-devel kf5-kxmlgui-devel kf5-kglobalaccel-devel pkgconfig pipewire-devel git`

works on Fedora 36, I don't if this could work on RedHat/CentOS/Rocky/Alma.

**Comment by RiemaruKarurosu** [comment]
I think it's for adding this to the Readme.MD at the build section.

**Comment by maltejur** [comment]
Sure, added
