### ISSUE TITLE
Application don't run at Ubuntu 22.04

### ISSUE THREAD

**Issue by turbo-cunnos** [maltejur/discord-screenaudio#64]
Hello, could anyone help me to understand what problem is.
Firstly I tried install the flat package, but nothing happen, Application won't start.
Secondly I tried to build from source. I didn't receive any errors, but application won't start too

When I tried to run it from terminal, I get message 
`[default] QLayout: Attempting to add QLayout "" to StreamDialog "", which already has a layout`

Tried to google it, but can't find solution without changing source code.

**Comment by maltejur** [comment]
The message you wrote probably has nothing to do with the error, that always occurs. The most probable cause of your problem is that you aren't running pipewire. Could you maybe check that? If that doesn't fix your issue, what distro and DE are you on?

**Comment by turbo-cunnos** [comment]
Yeah, you are right. I think if I have out of the box pipewire, that it works, but no.

I tried to replace pulse to pipewire with that guide https://ubuntuhandbook.org/index.php/2022/04/pipewire-replace-pulseaudio-ubuntu-2204/
but in final steps get timeout error of `pactl info`

So, thank you. I will try to solve that problems with pipewire.
