### ISSUE TITLE
No sound in screenshare

### ISSUE THREAD

**Issue by doubledge-spec** [maltejur/discord-screenaudio#7]
Platform is Arch Linux, on the Xfce Desktop Environment.

The virtual mic is created, audio is piped into that, but no sound from screenshare as told by peers.

I am unsure on how to get logs on this client.

**Comment by doubledge-spec** [comment]
Noisetorch causes an issue.
Maybe similar problem to easyeffects?

**Comment by shixgen** [comment]
> 

So is there no way to share screen audio and use noise torch at the same time?

**Comment by doubledge-spec** [comment]
[no_noisetorch.txt](https://github.com/maltejur/discord-screenaudio/files/9189972/no_noisetorch.txt)
[noisetorch.txt](https://github.com/maltejur/discord-screenaudio/files/9189973/noisetorch.txt)

**Comment by doubledge-spec** [comment]
another problem i've encountered is that i can't set the mic to be something else other than default, until I turn on the screenshare, which enables the virtmic, and then discord lets you choose because it detects two.

**Comment by maltejur** [comment]
Thanks for the logs. I can't find anything wrong about the virtmic there so I'll have to try out noisetorch myself.

**Comment by doubledge-spec** [comment]
> another problem i've encountered is that i can't set the mic to be something else other than default, until I turn on the screenshare, which enables the virtmic, and then discord lets you choose because it detects two.
 
I think this is also good to look into, maybe initialize the virtmic when the client starts? though i'm unsure how well that would work.

**Comment by maltejur** [comment]
Okay, I have tested noisetorch and everything works just fine for me. What is your configuration there?

**Comment by doubledge-spec** [comment]
I think my actual problem lied in the other problem i mentioned in issue #8

**Comment by shixgen** [comment]
I'm problems with sharing the audio still. Turned noise torch off. Using the "default" mic. This is what helvum is showing there is a virtmic, but not output on the stream. 

![image](https://user-images.githubusercontent.com/39845267/181016623-a5fd2c17-dfab-498f-a288-e5b5bfa36d41.png)
