### ISSUE TITLE
Can I use betterdiscord mods on this client?

### ISSUE THREAD

**Issue by ardishco-the-great** [maltejur/discord-screenaudio#76]
There is no file at ~/.config so I assume it's either not possible or the config file where I put all my modifications at is somewhere else?

**Comment by maltejur** [comment]
Hi, you can not use BetterDiscord with this client. I have some experimental work on client mods in https://github.com/maltejur/discord-screenaudio/issues/59, but that has a fraction of the betterdiscord features.

**Comment by ardishco-the-great** [comment]
Ah, okay. I see. So I am limited to what Web client mods there are available...That's fair enough. I love your work on this and will be using your client for years on end. Thanks for your service!
