### ISSUE TITLE
Unable to choose a different mic from Default on client launch.

### ISSUE THREAD

**Issue by doubledge-spec** [maltejur/discord-screenaudio#8]
another problem i've encountered is that i can't set the mic to be something else other than default until I turn on the screenshare which enables the virtmic, and then discord lets you choose because it detects two.

_Originally posted by @doubledge-spec in https://github.com/maltejur/discord-screenaudio/issues/7#issuecomment-1195454604_

**Comment by doubledge-spec** [comment]
In my past experience, this is intended behaviour by the discord webapp. It needs to detect two mic sources _after_ it's opened.

**Comment by maltejur** [comment]
Hmm interesting, you are right. If I start the virtmic 5 seconds after opening discord, all the audio devices show.

**Comment by doubledge-spec** [comment]
The discord website detects mic sources properly, on firefox it asks for access to both noisetorch and my builtin mic, then I can choose between them.
Chromium exhibits similar behavior to this client. I have to restart noisetorch, refresh the discord page and then both are detected.

**Comment by maltejur** [comment]
So should I just start a virtmic that does nothing 5 seconds after starting Discord? It sounds a bit hacky but if it works it works.

**Comment by doubledge-spec** [comment]
That's the only thing I can think of atm.

**Comment by maltejur** [comment]
Ok I'll do that then

**Comment by maltejur** [comment]
This should be fixed with https://github.com/maltejur/discord-screenaudio/commit/6492cb9a3590357423ab3bd9c587d7df2fe258f7. I found out that the point where discord asks chromium for microphone permission seems to be the perfect point to start a virtmic that does nothing.

**Comment by doubledge-spec** [comment]
awesome! if you could setup an aur -git package i'll test it asap
