### ISSUE TITLE
scaling

### ISSUE THREAD

**Issue by theeliapetti** [maltejur/discord-screenaudio#82]
I have a 3.5k laptop screen, the discord-screenaudio app (installed with yay) is very small. Unlike spotify I cannot use "ctrl +" to increase the scaling and there is no setting inside the app (to my knowledge) to increase it either. The regular discord app uses the correct scaling. Pls help. Also pop-out doesn't work.

**Comment by maltejur** [comment]
Hi. Since discord-screenaudio is a qt app, you can just use the `QT_SCALE_FACTOR` environment variable. This is either set by your DE, you can set it globally, or just start the client with `QT_SCALE_FACTOR=1.5 discord-screenaudio`. And making the pop-out work is out of scope for this project.
