### ISSUE TITLE
Feature Request: Use application.process.binary when application.name is an empty string

### ISSUE THREAD

**Issue by edisionnano** [maltejur/discord-screenaudio#89]
Some games on proton like Resident Evil or Deltarune have an empty application.name, the value of application.process.binary is wine64-preloader and it would be a good idea to show that instead.
Example from Resident Evil 7
![image](https://user-images.githubusercontent.com/26039434/214562539-d0759478-043c-47c4-93a8-c8138ec5214f.png)

**Comment by maltejur** [comment]
Sure. I've [updated the code](https://github.com/maltejur/discord-screenaudio/commit/bc317d5531ce3b2c4e5372ec19b24a32be09a9ed) and pushed it to the master branch. Could you test it and check if it works with your games?

**Comment by Jeames8kin** [comment]
Hey mate, just built `master` and checked with RE7 and RE2 with no success. No other programs apart from the ones with names show up so far, I might have to delve a little further as I just woke up.

Reading the output for `virtmic` doesn't seem to want to touch any program without a name either, so it's possibly not doing what we want it to. Screenshot below shows `discord-screenaudio` output, Discord itself being unable to find the game with the game running.

If you need more details/information, let me know and I'll be happy to provide anything else, as I was the one with this issue initially (thanks to @edisionnano for opening this issue).

![Resident_Evil_7_Discord_Screenaudio](https://user-images.githubusercontent.com/43592480/214680318-872df065-9ca0-4524-aa22-6e4867f0c295.png)

**Comment by maltejur** [comment]
I am having trouble trying to reproduce your problem. Even if I use the version of discord-screenaudio without the patch, everything works just fine:

![image](https://user-images.githubusercontent.com/48161361/214714063-c360f13e-9ad8-4257-8435-28ab095db3d9.png)![image](https://user-images.githubusercontent.com/48161361/214715273-9846e454-a1c9-4c24-bd23-de381d5c4465.png)

I am using the demo versions of the game here. Can you check if the [demo version of RE7](https://store.steampowered.com/app/530620/Resident_Evil_7_Teaser_Beginning_Hour/) also works for you?

**Comment by Jeames8kin** [comment]
Alright, so I just tested the demo and that shows up fine, but it actually has an entry under `application.name`, and on a technical level the demo of RE7 uses an older version of the RE Engine, before they changed it to DX12 and updated something regarding the audio, which RE2 got as well.

Are you using the DX11 version or the DX12 version of RE2? Might redownload the DX11 version to see if that's possibly the issue, as I don't think I recall this being a problem before the update now I come to think of it.

**Comment by maltejur** [comment]
Okay I just bought RE2 and 3, I wanted to play them sometime anyways and they are pretty cheap currently :D

With that I could reproduce your issue and fix it for real this time.

![image](https://user-images.githubusercontent.com/48161361/214723903-56d54ad8-a2bc-4dab-a289-cd19303bd5b8.png)

The changes are pushed to the master branch and you should be able to test them.

**Comment by Jeames8kin** [comment]
Something about the most recent RE Engine update has done something with the audio side of things, as the DX11 shows completely fine as shown in the screenshot below. Seems to be an RE Engine related issue, as all RE7, RE2 and RE3 are affected.

![RE2_Discord_Screenaudio](https://user-images.githubusercontent.com/43592480/214724523-08cfcbee-479c-479f-866f-242305117c8f.png)

I'll give the `master` branch another shot, however from my observation the no `application.name` issue stems from the latest RE Engine update to DirectX 12.

**Comment by Jeames8kin** [comment]
Yep, that definitely fixed it. `Wine64-preloader` shows up fine, game audio sounds fine to me through another Discord client, and it's the DX12 version.
![RE7_Discord_Screenaudio_Fixed](https://user-images.githubusercontent.com/43592480/214726682-361fd92d-719f-40c6-85c5-a99f21b48792.png)
Thanks for your (very quick) help, and enjoy the RE games! They're good fun to play, although I wish RE3 had a bit more time in the making, but it's still an alright game nonetheless. Hoping for RE4 Remake to be good, it's got me curious with their current approach to it.
