### ISSUE TITLE
Microphone sound is being piped into stream

### ISSUE THREAD

**Issue by shixgen** [maltejur/discord-screenaudio#9]
My microphone sound is being piped into the stream instead of whatever audio I choose to share. This is what helvum shows

![image](https://user-images.githubusercontent.com/39845267/181018421-70927891-f41f-4505-8817-27a8110d4c02.png)

[log.txt](https://github.com/maltejur/discord-screenaudio/files/9190229/log.txt)

**Comment by NelloKudo** [comment]
Try changing the microphone from default to your main one in Discord's settings and relaunch the app, it should behave the same as (this)[https://github.com/edisionnano/Screenshare-with-audio-on-Discord-with-Linux]

**Comment by doubledge-spec** [comment]
you are not supposed to use the Default mic, after the screenshare starts, select your normal mic in discord settings.

**Comment by shixgen** [comment]
> 

Ahh that is working now my bad. Thanks!

**Comment by doubledge-spec** [comment]
@shixgen issue #8  highlights the cause.
