### ISSUE TITLE
Close to Tray option missing from settings

### ISSUE THREAD

**Issue by ehea617** [maltejur/discord-screenaudio#90]
Pull request https://github.com/maltejur/discord-screenaudio/pull/88 - Implement Tray Icon does not work for me. The setting is missing from 'User Settings > My Account' as shown in the screenshot in the pull request.

Screenshot in the pull request:
![image](https://user-images.githubusercontent.com/12926544/214712257-2029d474-9187-4ca7-a6e2-c32b1ca28882.png)

Screenshot of my settings page:
![image](https://user-images.githubusercontent.com/12926544/214712189-6e66a756-a123-4e57-8ad9-82a495d1d023.png)

```
flatpak info de.shorsh.discord-screenaudio

discord-screenaudio - A custom discord client that supports streaming with
audio on Linux

          ID: de.shorsh.discord-screenaudio
         Ref: app/de.shorsh.discord-screenaudio/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 1.6.2
     License: GPL-3.0+
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 175.1 MB
     Runtime: org.kde.Platform/x86_64/5.15-21.08
         Sdk: org.kde.Sdk/x86_64/5.15-21.08

      Commit: 29a261d92d5c4e1d045f06391c826701e7fd3d9f3411b5a57c611ddad8c53349
      Parent: 9089eda5ed3fe19904651387f1dd847357cb5d0e9969884a4ef8c1801e4b4864
     Subject: v1.6.2 (#9) (fe1498f1)

```

Please let me know if there is any additional information you need to troubleshoot this issue.

**Comment by maltejur** [comment]
Thanks for reporting this, [it should be fixed](https://github.com/maltejur/discord-screenaudio/commit/2a809e163e78e3c89241b0dd0593a665cc63cde7). I will probably release the fix in the next days on flathub.
