### ISSUE TITLE
System tray icons not working on KDE

### ISSUE THREAD

**Issue by RiemaruKarurosu** [maltejur/discord-screenaudio#91]
closing discord-screenaudio doesn't create a system tray icon.

**Comment by RiemaruKarurosu** [comment]
It fixes adding to flatseal:
org.kde.*

**Comment by StellaSmith** [comment]
> It fixes adding to flatseal: org.kde.*

@RiemaruKarurosu  can you elaborate how to do it?

**Comment by RiemaruKarurosu** [comment]
> > It fixes adding to flatseal: org.kde.*
> 
> @RiemaruKarurosu can you elaborate how to do it?

Open Flatseal 

Add to session bus:

org.kde.*

restart the app

**Comment by maltejur** [comment]
Thanks for the hint @RiemaruKarurosu, this should now be properly fixed (https://github.com/flathub/de.shorsh.discord-screenaudio/commit/53c68cdcfe137838b0798dc0e9e3a89c55cf2b9d)
