### ISSUE TITLE
Does Not Launch on Linux Mint 

### ISSUE THREAD

**Issue by dungeon-mystic** [maltejur/discord-screenaudio#92]
When I click on the desktop icon to run the program, nothing happens.

**Comment by digieon** [comment]
Same here on my install. Doesn't open.

**Comment by digieon** [comment]
> Same here on my install. Doesn't open.

`jXXX@sXXX~$ flatpak run de.shorsh.discord-screenaudio
Gtk-Message: 02:00:30.498: Failed to load module "xapp-gtk3-module"
Qt: Session management error: None of the authentication protocols specified are supported
[2:15:0213/020030.831480:ERROR:address_tracker_linux.cc(214)] Could not bind NETLINK socket: Address already in use (98)
[default] QLayout: Attempting to add QLayout "" to StreamDialog "", which already has a layout
[default] QLayout: Attempting to add QLayout "" to StreamDialog "", which already has a layout
[default] QLayout: Attempting to add QLayout "" to StreamDialog "", which already has a layout
`
Linux Mint 21.1 Cinnamon

**Comment by digieon** [comment]
For anyone who finds this, Linux Mint does not currently have Pipewire enabled, I follow the instructions here and it is now working fine:
https://www.maketecheasier.com/install-configure-pipewire-linux/

**Comment by dungeon-mystic** [comment]
I switched to PipeWire and the application opens, but it cannot share the screen or audio. The share screen window pops up and when I click Start Stream nothing happens. (Not sure if you'll be notified of a new post on a closed issue @maltejur, so I'm tagging you)
