### ISSUE TITLE
Silent Launch on Startup

### ISSUE THREAD

**Issue by EmreDogu** [maltejur/discord-screenaudio#95]
Adding a toggle in the settings or at least a launch option where it allows it to start in background and can be fully opened by tray icon would be a nice feature. I think you can achieve it in regular discord by adding "--start-minimized" launch option.

**Comment by maltejur** [comment]
https://github.com/maltejur/discord-screenaudio/commit/0b12487dfd9595d17093dd91e325a28b3a0e8ce2
